### ISSUE TITLE
AI exam

### ISSUE THREAD

**Issue by matzar** [matt360/uni-links#6]
- [x] Academic AI vs Games AI
- [x] Finite State Machines
- [x] Rule Based Systems
- [x] Fuzzy Logic and FuSM
- [x] Reinforcement and Predictive
- [x] Genetic Algorithm
- [x] Case Based Reasoning
- [x] Artificial Neural Netowrks
- [x] Self-Organising Maps and Clustering
- [x] ART Networks
- [x] A-life & Intelligent Agents

**Comment by matt360** [comment]
Day 2
